<a href="https://colab.research.google.com/github/HumayunK01/Numpy-Assignment/blob/main/Pic_to_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Work on image using Numpy library:**

In [1]:
import PIL
print('Pillow Version:', PIL.__version__)

Pillow Version: 7.1.2


In [4]:
from PIL import Image
from numpy import asarray
# load the image
image = Image.open('abc.jpg')
# convert image to numpy array
data = asarray(image)
print(type(data))
# summarize shape
print(data.shape)

# create Pillow image
image2 = Image.fromarray(data)
print(type(image2))

# summarize image details
print(image2.mode)
print(image2.size)

<class 'numpy.ndarray'>
(2400, 3840, 3)
<class 'PIL.Image.Image'>
RGB
(3840, 2400)


In [5]:
print(data)

[[[ 13  55  71]
  [ 13  55  71]
  [ 13  55  71]
  ...
  [  7  25  35]
  [  8  26  36]
  [  9  27  37]]

 [[ 12  54  70]
  [ 12  54  70]
  [ 12  54  70]
  ...
  [  7  25  35]
  [  8  26  36]
  [  9  27  37]]

 [[ 11  53  69]
  [ 11  53  69]
  [ 11  53  69]
  ...
  [  8  26  36]
  [  8  26  36]
  [  8  26  36]]

 ...

 [[119 147 135]
  [118 146 134]
  [118 146 134]
  ...
  [  0   7  18]
  [  0   8  18]
  [  0   8  16]]

 [[114 146 133]
  [114 146 133]
  [115 145 133]
  ...
  [  0   8  18]
  [  0   8  18]
  [  0   8  18]]

 [[112 146 132]
  [112 146 132]
  [112 146 132]
  ...
  [  0   8  16]
  [  0   8  18]
  [  0   7  18]]]


In [6]:
print(data.shape)

(2400, 3840, 3)
